{% set version = '1.4-2.1' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-microbenchmark
  version: {{ version|replace("-", "_") }}

source:
  fn: microbenchmark_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/microbenchmark_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/microbenchmark/microbenchmark_{{ version }}.tar.gz
  sha256: 6feb06819b6a57346f24d7fc3f588ff60a236b5b170aa62383af456c54c8c562

build:
  merge_build_host: True  # [win]
  number: 1001
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - posix                # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
  host:
    - r-base
    - r-ggplot2
  run:
    - r-base
    - r-ggplot2

test:
  commands:
    - $R -e "library('microbenchmark')"  # [not win]
    - "\"%R%\" -e \"library('microbenchmark')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=microbenchmark
  license: BSD_2_clause
  summary: Provides infrastructure to accurately measure and compare the execution time of R
    expressions.
  license_family: BSD

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
