appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: bC331/6DWc6/DY4iO0K6NK0PynKLpB1zHeCaLmCqBFaVUQL++BKvyL9uM9d8JQ+M5kEvxSJvO295OOMLKFdzdbPgUUgri9DIUcDa6R6vCBRsHaZ+GHL4oD1rWDaO6UyHBsgz3j1oPkRs9+nNaQA+jTWoUerwQ1fQg9uSwtXr6+We3IUhcKR/Na7Qkf9GexHzlOSxzE83zP56nTmKaYGMJAjJ3LOG29e/Z4RJWUSfCgLFOc3QR6Nm5O1P5IfTLA5LbzJGSryXwpxdg7e45YtokpNJ39zqN3TV0Ze/6uEw0Xd5tRTwY78niCLUidWSc8Cc8oje2GaXJhuJz3vlBO9ml7u2RjkbX8EosNOH0GQ8EJhfoJC2BTXlcrJPFoClfKZ3l3LxsZJR+iFtGeIXMfg7h+ycWAxyyQPMxTAieqw5gO9sjqBmdEaWgZiGfYz6DyfoTn23b8hCGXUM5OnPw7LGzSscUgmolVyTXfU2FdB2cwilrFYCqrsh6sNOMXLJEJ+Ofkf6laMjU2Xym6ndjw+3hVx80e0GTHN/FiH9HmmxN5rBloJcqknTGKhkyNUom/HoSnkudXI/nNkb0Br9jE4B2nX/FgtEkW4o0CV6B93/am+Zo8WgyydJN0Cjvpn+DXWojbZjv5IFPbPgQ9I0VPqlF0NJfsa8oTcfQIzSO0vVEzM=}
